# Generated by Django 5.0.4 on 2024-04-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('number', models.IntegerField(max_length=50)),
            ],
        ),
    ]
