# Generated by Django 5.0.4 on 2024-04-25 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_users_email_alter_users_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='dob',
            field=models.IntegerField(),
        ),
    ]
