# Generated by Django 5.0.4 on 2024-04-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default=1211, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='token',
            field=models.CharField(max_length=500),
        ),
    ]
