# Generated by Django 5.0.4 on 2024-04-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_login_email_alter_login_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
