# Generated by Django 5.0.4 on 2024-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_login_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.AddField(
            model_name='users',
            name='socialLogin',
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
    ]
