# Generated by Django 5.0.4 on 2024-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_login_users_sociallogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=500, unique=True)),
                ('token', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
