# Generated by Django 5.0.4 on 2024-05-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='userID',
            field=models.CharField(default=110, max_length=250),
            preserve_default=False,
        ),
    ]
