# Generated by Django 5.0.4 on 2024-06-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_users_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='profileImage',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
