# Generated by Django 5.0.4 on 2024-06-11 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_users_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='number',
            field=models.BigIntegerField(null=True),
        ),
    ]
