# Generated by Django 5.0.4 on 2024-06-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_users_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='Isdeleted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
