# Generated by Django 5.0.4 on 2024-06-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cartID',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
