# Generated by Django 5.0.4 on 2024-06-27 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_users_cartid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=250, null=True)),
                ('cartID', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='cartID',
        ),
    ]
